//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreWebApplication.BookStoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://sigmaassignment.org/webservices")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        private double PriceField;
        
        private System.DateTime PublishDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime PublishDate {
            get {
                return this.PublishDateField;
            }
            set {
                if ((this.PublishDateField.Equals(value) != true)) {
                    this.PublishDateField = value;
                    this.RaisePropertyChanged("PublishDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sigmaassignment.org/webservices", ConfigurationName="BookStoreService.BookStoreWebServiceSoap")]
    public interface BookStoreWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name query from namespace http://sigmaassignment.org/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetAuthor", ReplyAction="*")]
        BookStoreWebApplication.BookStoreService.GetAuthorResponse GetAuthor(BookStoreWebApplication.BookStoreService.GetAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetAuthorResponse> GetAuthorAsync(BookStoreWebApplication.BookStoreService.GetAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://sigmaassignment.org/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetTitle", ReplyAction="*")]
        BookStoreWebApplication.BookStoreService.GetTitleResponse GetTitle(BookStoreWebApplication.BookStoreService.GetTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetTitleResponse> GetTitleAsync(BookStoreWebApplication.BookStoreService.GetTitleRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://sigmaassignment.org/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetGenre", ReplyAction="*")]
        BookStoreWebApplication.BookStoreService.GetGenreResponse GetGenre(BookStoreWebApplication.BookStoreService.GetGenreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetGenre", ReplyAction="*")]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetGenreResponse> GetGenreAsync(BookStoreWebApplication.BookStoreService.GetGenreRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://sigmaassignment.org/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetID", ReplyAction="*")]
        BookStoreWebApplication.BookStoreService.GetIDResponse GetID(BookStoreWebApplication.BookStoreService.GetIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetID", ReplyAction="*")]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetIDResponse> GetIDAsync(BookStoreWebApplication.BookStoreService.GetIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://sigmaassignment.org/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetAll", ReplyAction="*")]
        BookStoreWebApplication.BookStoreService.GetAllResponse GetAll(BookStoreWebApplication.BookStoreService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sigmaassignment.org/webservices/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetAllResponse> GetAllAsync(BookStoreWebApplication.BookStoreService.GetAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthor", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetAuthorRequestBody Body;
        
        public GetAuthorRequest() {
        }
        
        public GetAuthorRequest(BookStoreWebApplication.BookStoreService.GetAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetAuthorRequestBody() {
        }
        
        public GetAuthorRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorResponse", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetAuthorResponseBody Body;
        
        public GetAuthorResponse() {
        }
        
        public GetAuthorResponse(BookStoreWebApplication.BookStoreService.GetAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookStoreWebApplication.BookStoreService.Book[] GetAuthorResult;
        
        public GetAuthorResponseBody() {
        }
        
        public GetAuthorResponseBody(BookStoreWebApplication.BookStoreService.Book[] GetAuthorResult) {
            this.GetAuthorResult = GetAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitle", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetTitleRequestBody Body;
        
        public GetTitleRequest() {
        }
        
        public GetTitleRequest(BookStoreWebApplication.BookStoreService.GetTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetTitleRequestBody() {
        }
        
        public GetTitleRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTitleResponse", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetTitleResponseBody Body;
        
        public GetTitleResponse() {
        }
        
        public GetTitleResponse(BookStoreWebApplication.BookStoreService.GetTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookStoreWebApplication.BookStoreService.Book[] GetTitleResult;
        
        public GetTitleResponseBody() {
        }
        
        public GetTitleResponseBody(BookStoreWebApplication.BookStoreService.Book[] GetTitleResult) {
            this.GetTitleResult = GetTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenre", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetGenreRequestBody Body;
        
        public GetGenreRequest() {
        }
        
        public GetGenreRequest(BookStoreWebApplication.BookStoreService.GetGenreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetGenreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetGenreRequestBody() {
        }
        
        public GetGenreRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenreResponse", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetGenreResponseBody Body;
        
        public GetGenreResponse() {
        }
        
        public GetGenreResponse(BookStoreWebApplication.BookStoreService.GetGenreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetGenreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookStoreWebApplication.BookStoreService.Book[] GetGenreResult;
        
        public GetGenreResponseBody() {
        }
        
        public GetGenreResponseBody(BookStoreWebApplication.BookStoreService.Book[] GetGenreResult) {
            this.GetGenreResult = GetGenreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetID", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetIDRequestBody Body;
        
        public GetIDRequest() {
        }
        
        public GetIDRequest(BookStoreWebApplication.BookStoreService.GetIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public GetIDRequestBody() {
        }
        
        public GetIDRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIDResponse", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetIDResponseBody Body;
        
        public GetIDResponse() {
        }
        
        public GetIDResponse(BookStoreWebApplication.BookStoreService.GetIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookStoreWebApplication.BookStoreService.Book[] GetIDResult;
        
        public GetIDResponseBody() {
        }
        
        public GetIDResponseBody(BookStoreWebApplication.BookStoreService.Book[] GetIDResult) {
            this.GetIDResult = GetIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(BookStoreWebApplication.BookStoreService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://sigmaassignment.org/webservices", Order=0)]
        public BookStoreWebApplication.BookStoreService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(BookStoreWebApplication.BookStoreService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sigmaassignment.org/webservices")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BookStoreWebApplication.BookStoreService.Book[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(BookStoreWebApplication.BookStoreService.Book[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookStoreWebServiceSoapChannel : BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookStoreWebServiceSoapClient : System.ServiceModel.ClientBase<BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap>, BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap {
        
        public BookStoreWebServiceSoapClient() {
        }
        
        public BookStoreWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookStoreWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStoreWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStoreWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookStoreWebApplication.BookStoreService.GetAuthorResponse BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetAuthor(BookStoreWebApplication.BookStoreService.GetAuthorRequest request) {
            return base.Channel.GetAuthor(request);
        }
        
        public BookStoreWebApplication.BookStoreService.Book[] GetAuthor(string query) {
            BookStoreWebApplication.BookStoreService.GetAuthorRequest inValue = new BookStoreWebApplication.BookStoreService.GetAuthorRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetAuthorRequestBody();
            inValue.Body.query = query;
            BookStoreWebApplication.BookStoreService.GetAuthorResponse retVal = ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetAuthor(inValue);
            return retVal.Body.GetAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetAuthorResponse> BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetAuthorAsync(BookStoreWebApplication.BookStoreService.GetAuthorRequest request) {
            return base.Channel.GetAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetAuthorResponse> GetAuthorAsync(string query) {
            BookStoreWebApplication.BookStoreService.GetAuthorRequest inValue = new BookStoreWebApplication.BookStoreService.GetAuthorRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetAuthorRequestBody();
            inValue.Body.query = query;
            return ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookStoreWebApplication.BookStoreService.GetTitleResponse BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetTitle(BookStoreWebApplication.BookStoreService.GetTitleRequest request) {
            return base.Channel.GetTitle(request);
        }
        
        public BookStoreWebApplication.BookStoreService.Book[] GetTitle(string query) {
            BookStoreWebApplication.BookStoreService.GetTitleRequest inValue = new BookStoreWebApplication.BookStoreService.GetTitleRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetTitleRequestBody();
            inValue.Body.query = query;
            BookStoreWebApplication.BookStoreService.GetTitleResponse retVal = ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetTitle(inValue);
            return retVal.Body.GetTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetTitleResponse> BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetTitleAsync(BookStoreWebApplication.BookStoreService.GetTitleRequest request) {
            return base.Channel.GetTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetTitleResponse> GetTitleAsync(string query) {
            BookStoreWebApplication.BookStoreService.GetTitleRequest inValue = new BookStoreWebApplication.BookStoreService.GetTitleRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetTitleRequestBody();
            inValue.Body.query = query;
            return ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookStoreWebApplication.BookStoreService.GetGenreResponse BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetGenre(BookStoreWebApplication.BookStoreService.GetGenreRequest request) {
            return base.Channel.GetGenre(request);
        }
        
        public BookStoreWebApplication.BookStoreService.Book[] GetGenre(string query) {
            BookStoreWebApplication.BookStoreService.GetGenreRequest inValue = new BookStoreWebApplication.BookStoreService.GetGenreRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetGenreRequestBody();
            inValue.Body.query = query;
            BookStoreWebApplication.BookStoreService.GetGenreResponse retVal = ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetGenre(inValue);
            return retVal.Body.GetGenreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetGenreResponse> BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetGenreAsync(BookStoreWebApplication.BookStoreService.GetGenreRequest request) {
            return base.Channel.GetGenreAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetGenreResponse> GetGenreAsync(string query) {
            BookStoreWebApplication.BookStoreService.GetGenreRequest inValue = new BookStoreWebApplication.BookStoreService.GetGenreRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetGenreRequestBody();
            inValue.Body.query = query;
            return ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetGenreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookStoreWebApplication.BookStoreService.GetIDResponse BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetID(BookStoreWebApplication.BookStoreService.GetIDRequest request) {
            return base.Channel.GetID(request);
        }
        
        public BookStoreWebApplication.BookStoreService.Book[] GetID(string query) {
            BookStoreWebApplication.BookStoreService.GetIDRequest inValue = new BookStoreWebApplication.BookStoreService.GetIDRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetIDRequestBody();
            inValue.Body.query = query;
            BookStoreWebApplication.BookStoreService.GetIDResponse retVal = ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetID(inValue);
            return retVal.Body.GetIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetIDResponse> BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetIDAsync(BookStoreWebApplication.BookStoreService.GetIDRequest request) {
            return base.Channel.GetIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetIDResponse> GetIDAsync(string query) {
            BookStoreWebApplication.BookStoreService.GetIDRequest inValue = new BookStoreWebApplication.BookStoreService.GetIDRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetIDRequestBody();
            inValue.Body.query = query;
            return ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookStoreWebApplication.BookStoreService.GetAllResponse BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetAll(BookStoreWebApplication.BookStoreService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public BookStoreWebApplication.BookStoreService.Book[] GetAll() {
            BookStoreWebApplication.BookStoreService.GetAllRequest inValue = new BookStoreWebApplication.BookStoreService.GetAllRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetAllRequestBody();
            BookStoreWebApplication.BookStoreService.GetAllResponse retVal = ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetAllResponse> BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap.GetAllAsync(BookStoreWebApplication.BookStoreService.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookStoreWebApplication.BookStoreService.GetAllResponse> GetAllAsync() {
            BookStoreWebApplication.BookStoreService.GetAllRequest inValue = new BookStoreWebApplication.BookStoreService.GetAllRequest();
            inValue.Body = new BookStoreWebApplication.BookStoreService.GetAllRequestBody();
            return ((BookStoreWebApplication.BookStoreService.BookStoreWebServiceSoap)(this)).GetAllAsync(inValue);
        }
    }
}
